// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Loans.API.Infraestructure.DBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Loans.API.Data
{
    public partial class LOANSContext : DbContext
    {
        public LOANSContext()
        {
        }

        public LOANSContext(DbContextOptions<LOANSContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Avales> Avales { get; set; }
        public virtual DbSet<ClienteConyugue> ClienteConyugue { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<EvaluacionFinanciera> EvaluacionFinanciera { get; set; }
        public virtual DbSet<Garantias> Garantias { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<ReferenciasPersonales> ReferenciasPersonales { get; set; }
        public virtual DbSet<Solicitudes> Solicitudes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=desktop-csf7eun\\sqlexpress;Initial Catalog=LRP_LOANS_MS_DEV;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}