// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Loans.API.Infraestructure.DBModels
{
    [Table("clientes")]
    public partial class Clientes
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idHash")]
        [StringLength(255)]
        [Unicode(false)]
        public string IdHash { get; set; }
        [Column("cliente")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cliente { get; set; }
        [Column("cedula")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cedula { get; set; }
        [Column("nombres")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nombres { get; set; }
        [Column("apellidos")]
        [StringLength(50)]
        [Unicode(false)]
        public string Apellidos { get; set; }
        [Column("fchNacim", TypeName = "date")]
        public DateTime? FchNacim { get; set; }
        [Column("direccion1")]
        [StringLength(50)]
        [Unicode(false)]
        public string Direccion1 { get; set; }
        [Column("direccion2")]
        [StringLength(50)]
        [Unicode(false)]
        public string Direccion2 { get; set; }
        [Column("codPais")]
        public int? CodPais { get; set; }
        [Column("codDepto")]
        public int? CodDepto { get; set; }
        [Column("codCiudad")]
        public int? CodCiudad { get; set; }
        [Column("codAldea")]
        public int? CodAldea { get; set; }
        [Column("codLugpob")]
        public int? CodLugpob { get; set; }
        [Column("codAgencia")]
        [StringLength(50)]
        [Unicode(false)]
        public string CodAgencia { get; set; }
        [Column("lugarNacim")]
        [StringLength(50)]
        [Unicode(false)]
        public string LugarNacim { get; set; }
        [Column("tipoDeId")]
        [StringLength(50)]
        [Unicode(false)]
        public string TipoDeId { get; set; }
        [Column("haSolicitadoCreditos")]
        public int? HaSolicitadoCreditos { get; set; }
        [Column("montoUltimoCredito", TypeName = "decimal(10, 2)")]
        public decimal? MontoUltimoCredito { get; set; }
        [Column("fechaUtimoCredito", TypeName = "date")]
        public DateTime? FechaUtimoCredito { get; set; }
        [Column("pagoUtimoCredito")]
        [StringLength(50)]
        [Unicode(false)]
        public string PagoUtimoCredito { get; set; }
        [Column("email")]
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column("rtn")]
        [StringLength(50)]
        [Unicode(false)]
        public string Rtn { get; set; }
        [Column("telefono")]
        [StringLength(50)]
        [Unicode(false)]
        public string Telefono { get; set; }
        [Column("contacto")]
        [StringLength(50)]
        [Unicode(false)]
        public string Contacto { get; set; }
        [Column("telContacto")]
        [StringLength(50)]
        [Unicode(false)]
        public string TelContacto { get; set; }
        [Column("tpCliente")]
        public int? TpCliente { get; set; }
        [Column("ocupacion")]
        [StringLength(50)]
        [Unicode(false)]
        public string Ocupacion { get; set; }
        [Column("grpEcon")]
        public int? GrpEcon { get; set; }
        [Column("empresa")]
        [StringLength(50)]
        [Unicode(false)]
        public string Empresa { get; set; }
        [Column("fchIngreso", TypeName = "date")]
        public DateTime? FchIngreso { get; set; }
        [Column("sueldo", TypeName = "decimal(10, 2)")]
        public decimal? Sueldo { get; set; }
        [Column("tipoEmp")]
        [StringLength(50)]
        [Unicode(false)]
        public string TipoEmp { get; set; }
        [Column("estCiv")]
        [StringLength(50)]
        [Unicode(false)]
        public string EstCiv { get; set; }
        [Column("nivEdu")]
        public int? NivEdu { get; set; }
        [Column("sexo")]
        [StringLength(50)]
        [Unicode(false)]
        public string Sexo { get; set; }
        [Column("nombEmpresa")]
        [StringLength(50)]
        [Unicode(false)]
        public string NombEmpresa { get; set; }
        [Column("cantEmpEmpresa")]
        public int? CantEmpEmpresa { get; set; }
        [Column("direccion1Empresa")]
        [StringLength(50)]
        [Unicode(false)]
        public string Direccion1Empresa { get; set; }
        [Column("direccion2Empresa")]
        [StringLength(50)]
        [Unicode(false)]
        public string Direccion2Empresa { get; set; }
        [Column("codCiudEmpresa")]
        [StringLength(50)]
        [Unicode(false)]
        public string CodCiudEmpresa { get; set; }
        [Column("telefonoEmpresa")]
        [StringLength(50)]
        [Unicode(false)]
        public string TelefonoEmpresa { get; set; }
        [Column("frecEval")]
        public int? FrecEval { get; set; }
        [Column("oficial")]
        public int? Oficial { get; set; }
        [Column("fchCreado", TypeName = "datetime")]
        public DateTime? FchCreado { get; set; }
        [Column("creadoPor")]
        [StringLength(50)]
        [Unicode(false)]
        public string CreadoPor { get; set; }
        [Column("telMovil")]
        [StringLength(50)]
        [Unicode(false)]
        public string TelMovil { get; set; }
        [Column("fchPgosal", TypeName = "date")]
        public DateTime? FchPgosal { get; set; }
        [Column("tpRelacion")]
        [StringLength(50)]
        [Unicode(false)]
        public string TpRelacion { get; set; }
        [Column("tpedivisa")]
        [StringLength(50)]
        [Unicode(false)]
        public string Tpedivisa { get; set; }
        [Column("dependencia")]
        [StringLength(50)]
        [Unicode(false)]
        public string Dependencia { get; set; }
        [Column("cargo")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cargo { get; set; }
        [Column("fchInicio", TypeName = "date")]
        public DateTime? FchInicio { get; set; }
        [Column("otrosing", TypeName = "decimal(10, 2)")]
        public decimal? Otrosing { get; set; }
        [Column("detalleOtrosing")]
        [StringLength(50)]
        [Unicode(false)]
        public string DetalleOtrosing { get; set; }
        [Column("gpsLatitud")]
        [StringLength(50)]
        [Unicode(false)]
        public string GpsLatitud { get; set; }
        [Column("gpsLongitud")]
        [StringLength(50)]
        [Unicode(false)]
        public string GpsLongitud { get; set; }
        [Column("tpResidencia")]
        [StringLength(50)]
        [Unicode(false)]
        public string TpResidencia { get; set; }
        [Column("nDependiente")]
        public int? NDependiente { get; set; }
        [Column("catDeudor")]
        public int? CatDeudor { get; set; }
        [Column("catDeudorAutom")]
        public int? CatDeudorAutom { get; set; }
        [Column("codPaisDeId")]
        public int? CodPaisDeId { get; set; }
        [Column("sector")]
        [StringLength(50)]
        [Unicode(false)]
        public string Sector { get; set; }
        [Column("hijosDependientes")]
        public int? HijosDependientes { get; set; }
        [Column("leer")]
        public int? Leer { get; set; }
        [Column("escribir")]
        public int? Escribir { get; set; }
        [Column("aceptaMensaje")]
        public int? AceptaMensaje { get; set; }
        [Column("codTiempoResidir")]
        public int? CodTiempoResidir { get; set; }
        [Column("sueldoTotSemanal", TypeName = "decimal(10, 2)")]
        public decimal? SueldoTotSemanal { get; set; }
        [Column("sueldoTotCatorcenal", TypeName = "decimal(10, 2)")]
        public decimal? SueldoTotCatorcenal { get; set; }
        [Column("esfuncPublico")]
        [StringLength(50)]
        [Unicode(false)]
        public string EsfuncPublico { get; set; }
        [Column("cargoPublico")]
        [StringLength(50)]
        [Unicode(false)]
        public string CargoPublico { get; set; }
        [Column("origen")]
        [StringLength(50)]
        [Unicode(false)]
        public string Origen { get; set; }
        [Column("formaPgo")]
        public int? FormaPgo { get; set; }
        [Column("codOcupacion")]
        public int? CodOcupacion { get; set; }
    }
}