// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Loans.API.Infraestructure.DBModels
{
    [Table("garantias")]
    public partial class Garantias
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idHash")]
        [StringLength(250)]
        [Unicode(false)]
        public string IdHash { get; set; }
        [Column("aval")]
        [StringLength(50)]
        [Unicode(false)]
        public string Aval { get; set; }
        [Column("tpgarantiam")]
        public int? Tpgarantiam { get; set; }
        [Column("clsGarantia")]
        public int? ClsGarantia { get; set; }
        [Column("tpbien")]
        public int? Tpbien { get; set; }
        [Column("marca")]
        [StringLength(50)]
        [Unicode(false)]
        public string Marca { get; set; }
        [Column("modelo")]
        [StringLength(50)]
        [Unicode(false)]
        public string Modelo { get; set; }
        [Column("tipo")]
        [StringLength(50)]
        [Unicode(false)]
        public string Tipo { get; set; }
        [Column("color")]
        [StringLength(50)]
        [Unicode(false)]
        public string Color { get; set; }
        [Column("motor")]
        [StringLength(50)]
        [Unicode(false)]
        public string Motor { get; set; }
        [Column("chasis")]
        [StringLength(50)]
        [Unicode(false)]
        public string Chasis { get; set; }
        [Column("vin")]
        [StringLength(50)]
        [Unicode(false)]
        public string Vin { get; set; }
        [Column("anio")]
        public int? Anio { get; set; }
        [Column("cilindraje")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cilindraje { get; set; }
        [Column("numPlaca")]
        [StringLength(50)]
        [Unicode(false)]
        public string NumPlaca { get; set; }
        [Column("nomValuador")]
        [StringLength(50)]
        [Unicode(false)]
        public string NomValuador { get; set; }
        [Column("tpidentificacion")]
        [StringLength(50)]
        [Unicode(false)]
        public string Tpidentificacion { get; set; }
        [Column("numIdentificacion")]
        [StringLength(50)]
        [Unicode(false)]
        public string NumIdentificacion { get; set; }
        [Column("descAvaluo")]
        [StringLength(50)]
        [Unicode(false)]
        public string DescAvaluo { get; set; }
        [Column("descNotaria")]
        [StringLength(50)]
        [Unicode(false)]
        public string DescNotaria { get; set; }
        [Column("serie")]
        [StringLength(50)]
        [Unicode(false)]
        public string Serie { get; set; }
        [Column("cantSemovientes")]
        public int? CantSemovientes { get; set; }
        [Column("raza")]
        [StringLength(50)]
        [Unicode(false)]
        public string Raza { get; set; }
        [Column("codCustodia")]
        [StringLength(50)]
        [Unicode(false)]
        public string CodCustodia { get; set; }
        [Column("fchEntrega", TypeName = "datetime")]
        public DateTime? FchEntrega { get; set; }
        [Column("responsable")]
        [StringLength(50)]
        [Unicode(false)]
        public string Responsable { get; set; }
        [Column("lugar")]
        [StringLength(50)]
        [Unicode(false)]
        public string Lugar { get; set; }
        [Column("telCustodia")]
        [StringLength(50)]
        [Unicode(false)]
        public string TelCustodia { get; set; }
        [Column("infoCustodia")]
        [StringLength(50)]
        [Unicode(false)]
        public string InfoCustodia { get; set; }
        [Column("avalReferencia")]
        [StringLength(50)]
        [Unicode(false)]
        public string AvalReferencia { get; set; }
        [Column("codDepto")]
        public int? CodDepto { get; set; }
        [Column("codCiud")]
        public int? CodCiud { get; set; }
        [Column("codAldea")]
        public int? CodAldea { get; set; }
        [Column("tpaval")]
        public int? Tpaval { get; set; }
        [Column("tipoHipoteca")]
        public int? TipoHipoteca { get; set; }
        [Column("idTpgarantiaHipo")]
        public int? IdTpgarantiaHipo { get; set; }
        [Column("fchSuscripcion", TypeName = "datetime")]
        public DateTime? FchSuscripcion { get; set; }
        [Column("fchVencimiento", TypeName = "datetime")]
        public DateTime? FchVencimiento { get; set; }
        [Column("tieneSeguro")]
        public int? TieneSeguro { get; set; }
        [Column("tipoCobertura")]
        [StringLength(50)]
        [Unicode(false)]
        public string TipoCobertura { get; set; }
        [Column("aseguradora")]
        [StringLength(50)]
        [Unicode(false)]
        public string Aseguradora { get; set; }
        [Column("telAsegu")]
        [StringLength(50)]
        [Unicode(false)]
        public string TelAsegu { get; set; }
        [Column("valorProyectado")]
        public int? ValorProyectado { get; set; }
        [Column("numContrato")]
        [StringLength(50)]
        [Unicode(false)]
        public string NumContrato { get; set; }
    }
}