// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Loans.API.Models
{
    [Table("avales")]
    public partial class Avales
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idHash")]
        [StringLength(255)]
        [Unicode(false)]
        public string IdHash { get; set; }
        [Column("aval")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval { get; set; }
        [Column("nombre")]
        [StringLength(255)]
        [Unicode(false)]
        public string Nombre { get; set; }
        [Column("empresa")]
        [StringLength(255)]
        [Unicode(false)]
        public string Empresa { get; set; }
        [Column("direccion")]
        [StringLength(255)]
        [Unicode(false)]
        public string Direccion { get; set; }
        [Column("codCiud")]
        public int? CodCiud { get; set; }
        [Column("codDepto")]
        public int? CodDepto { get; set; }
        [Column("codAldea")]
        public int? CodAldea { get; set; }
        [Column("clsAval")]
        public int? ClsAval { get; set; }
        [Column("telefono")]
        [StringLength(255)]
        [Unicode(false)]
        public string Telefono { get; set; }
        [Column("estatus")]
        public int? Estatus { get; set; }
        [Column("ingreso")]
        public int? Ingreso { get; set; }
        [Column("tipoDeId")]
        [StringLength(255)]
        [Unicode(false)]
        public string TipoDeId { get; set; }
        [Column("idcl")]
        [StringLength(255)]
        [Unicode(false)]
        public string Idcl { get; set; }
        [Column("operador")]
        [StringLength(255)]
        [Unicode(false)]
        public string Operador { get; set; }
        [Column("fchCreado", TypeName = "datetime")]
        public DateTime? FchCreado { get; set; }
        [Column("creadoPor")]
        [StringLength(255)]
        [Unicode(false)]
        public string CreadoPor { get; set; }
        [Column("telMovil")]
        [StringLength(255)]
        [Unicode(false)]
        public string TelMovil { get; set; }
        [Column("sexo")]
        [StringLength(255)]
        [Unicode(false)]
        public string Sexo { get; set; }
        [Column("pais")]
        public int? Pais { get; set; }
        [Column("tprelacion")]
        [StringLength(255)]
        [Unicode(false)]
        public string Tprelacion { get; set; }
        [Column("comentario")]
        [StringLength(255)]
        [Unicode(false)]
        public string Comentario { get; set; }
        [Column("claseg")]
        [StringLength(255)]
        [Unicode(false)]
        public string Claseg { get; set; }
        [Column("fchEscritura", TypeName = "datetime")]
        public DateTime? FchEscritura { get; set; }
        [Column("folioConstitucion")]
        [StringLength(255)]
        [Unicode(false)]
        public string FolioConstitucion { get; set; }
        [Column("notaria")]
        [StringLength(255)]
        [Unicode(false)]
        public string Notaria { get; set; }
        [Column("anioConstitucion", TypeName = "datetime")]
        public DateTime? AnioConstitucion { get; set; }
        [Column("noConstitucion")]
        public int? NoConstitucion { get; set; }
        [Column("fchAdq", TypeName = "datetime")]
        public DateTime? FchAdq { get; set; }
        [Column("gpsLatitud")]
        [StringLength(255)]
        [Unicode(false)]
        public string GpsLatitud { get; set; }
        [Column("gpsLongitud")]
        [StringLength(255)]
        [Unicode(false)]
        public string GpsLongitud { get; set; }
        [Column("paisDeId")]
        public int? PaisDeId { get; set; }
        [Column("codubi")]
        [StringLength(255)]
        [Unicode(false)]
        public string Codubi { get; set; }
        [Column("sector")]
        [StringLength(255)]
        [Unicode(false)]
        public string Sector { get; set; }
        [Column("codDeptoNac")]
        public int? CodDeptoNac { get; set; }
        [Column("numCiudNac")]
        public int? NumCiudNac { get; set; }
        [Column("codAldeaNac")]
        public int? CodAldeaNac { get; set; }
        [Column("profesion")]
        [StringLength(255)]
        [Unicode(false)]
        public string Profesion { get; set; }
        [Column("tipoIdentificacion")]
        public int? TipoIdentificacion { get; set; }
        [Column("referPersonal")]
        [StringLength(255)]
        [Unicode(false)]
        public string ReferPersonal { get; set; }
        [Column("referCedula")]
        [StringLength(255)]
        [Unicode(false)]
        public string ReferCedula { get; set; }
        [Column("referTelFijo")]
        [StringLength(255)]
        [Unicode(false)]
        public string ReferTelFijo { get; set; }
        [Column("referTelMovil")]
        [StringLength(255)]
        [Unicode(false)]
        public string ReferTelMovil { get; set; }
        [Column("estadoCivil")]
        public int? EstadoCivil { get; set; }
        [Column("giroEmpleo")]
        [StringLength(255)]
        [Unicode(false)]
        public string GiroEmpleo { get; set; }
        [Column("negocioPropio")]
        [StringLength(255)]
        [Unicode(false)]
        public string NegocioPropio { get; set; }
        [Column("fuenteIngreso")]
        [StringLength(255)]
        [Unicode(false)]
        public string FuenteIngreso { get; set; }
        [Column("datosLaborales")]
        [StringLength(255)]
        [Unicode(false)]
        public string DatosLaborales { get; set; }
        [Column("tpaval")]
        public int? Tpaval { get; set; }
        [Column("nombComer")]
        [StringLength(255)]
        [Unicode(false)]
        public string NombComer { get; set; }
        [Column("rlNombre")]
        [StringLength(255)]
        [Unicode(false)]
        public string RlNombre { get; set; }
        [Column("rlFchNac", TypeName = "datetime")]
        public DateTime? RlFchNac { get; set; }
        [Column("rlLugarNac")]
        [StringLength(255)]
        [Unicode(false)]
        public string RlLugarNac { get; set; }
        [Column("rlProfesion")]
        [StringLength(255)]
        [Unicode(false)]
        public string RlProfesion { get; set; }
        [Column("rlNacionalidad")]
        public int? RlNacionalidad { get; set; }
        [Column("rlGenero")]
        [StringLength(255)]
        [Unicode(false)]
        public string RlGenero { get; set; }
        [Column("rlId")]
        [StringLength(255)]
        [Unicode(false)]
        public string RlId { get; set; }
        [Column("rlTipoId")]
        public int? RlTipoId { get; set; }
        [Column("rlCodDepto")]
        public int? RlCodDepto { get; set; }
        [Column("rlCodCiud")]
        public int? RlCodCiud { get; set; }
        [Column("rlCodAldea")]
        public int? RlCodAldea { get; set; }
        [Column("rlDir1")]
        [StringLength(255)]
        [Unicode(false)]
        public string RlDir1 { get; set; }
        [Column("cobertura")]
        public int? Cobertura { get; set; }
        [Column("regProToma")]
        [StringLength(255)]
        [Unicode(false)]
        public string RegProToma { get; set; }
        [Column("regProFolio")]
        [StringLength(255)]
        [Unicode(false)]
        public string RegProFolio { get; set; }
        [Column("rtn")]
        [StringLength(255)]
        [Unicode(false)]
        public string Rtn { get; set; }
        [Column("codLugpob")]
        public int? CodLugpob { get; set; }
    }
}