// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Loans.API.Models
{
    [Table("evaluacion_financiera")]
    public partial class EvaluacionFinanciera
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idHash")]
        [StringLength(255)]
        [Unicode(false)]
        public string IdHash { get; set; }
        [Column("v_buena")]
        public double? VBuena { get; set; }
        [Column("v_regular")]
        public double? VRegular { get; set; }
        [Column("v_baja")]
        public double? VBaja { get; set; }
        [Column("v_reccxc")]
        public double? VReccxc { get; set; }
        [Column("vtot_mensual")]
        public double? VtotMensual { get; set; }
        [Column("oingre_conyugue")]
        public double? OingreConyugue { get; set; }
        [Column("oingre_otrosneg")]
        public double? OingreOtrosneg { get; set; }
        [Column("oingre_remesas")]
        public double? OingreRemesas { get; set; }
        [Column("oingre_salarios")]
        public double? OingreSalarios { get; set; }
        [Column("gopere_alquiler")]
        public double? GopereAlquiler { get; set; }
        [Column("gopere_agua")]
        public double? GopereAgua { get; set; }
        [Column("gopere_electri")]
        public double? GopereElectri { get; set; }
        [Column("gopere_telefono")]
        public double? GopereTelefono { get; set; }
        [Column("gopere_impuesto")]
        public double? GopereImpuesto { get; set; }
        [Column("gopere_trans")]
        public double? GopereTrans { get; set; }
        [Column("goper_esalarios")]
        public double? GoperEsalarios { get; set; }
        [Column("gopere_mantrenta")]
        public double? GopereMantrenta { get; set; }
        [Column("gopere_gas")]
        public double? GopereGas { get; set; }
        [Column("gopere_ctasprest")]
        public double? GopereCtasprest { get; set; }
        [Column("gopere_otros")]
        public double? GopereOtros { get; set; }
        [Column("gopere_total")]
        public double? GopereTotal { get; set; }
        [Column("gasfam_alimen")]
        public double? GasfamAlimen { get; set; }
        [Column("gasfam_vestu")]
        public double? GasfamVestu { get; set; }
        [Column("gasfam_vivie")]
        public double? GasfamVivie { get; set; }
        [Column("gasfam_salud")]
        public double? GasfamSalud { get; set; }
        [Column("gasfam_educa")]
        public double? GasfamEduca { get; set; }
        [Column("gasfam_transpor")]
        public double? GasfamTranspor { get; set; }
        [Column("gasfam_agua")]
        public double? GasfamAgua { get; set; }
        [Column("gasfam_electri")]
        public double? GasfamElectri { get; set; }
        [Column("gasfam_gas")]
        public double? GasfamGas { get; set; }
        [Column("gasfam_telefono")]
        public double? GasfamTelefono { get; set; }
        [Column("gasfam_otros")]
        public double? GasfamOtros { get; set; }
        [Column("gasfam_total")]
        public double? GasfamTotal { get; set; }
        [Column("estgana_ingreven")]
        public double? EstganaIngreven { get; set; }
        [Column("estgana_cosvent")]
        public double? EstganaCosvent { get; set; }
        [Column("estgana_utibrut")]
        public double? EstganaUtibrut { get; set; }
        [Column("estgana_gastope")]
        public double? EstganaGastope { get; set; }
        [Column("estgana_utioper")]
        public double? EstganaUtioper { get; set; }
        [Column("estgana_gastfam")]
        public double? EstganaGastfam { get; set; }
        [Column("estgana_otro")]
        public double? EstganaOtro { get; set; }
        [Column("estgana_ganneta")]
        public double? EstganaGanneta { get; set; }
        [Column("estgana_marconfi")]
        public double? EstganaMarconfi { get; set; }
        [Column("ganajus_mensu")]
        public double? GanajusMensu { get; set; }
        [Column("ganajus_cator")]
        public double? GanajusCator { get; set; }
        [Column("ganajus_sema")]
        public double? GanajusSema { get; set; }
        [Column("ganajus_ingre")]
        public double? GanajusIngre { get; set; }
        [Column("ganajus_egre")]
        public double? GanajusEgre { get; set; }
        [Column("ganajus_vent")]
        public double? GanajusVent { get; set; }
        [Column("ganajus_ultneta")]
        public double? GanajusUltneta { get; set; }
        [Column("patri_efec")]
        public double? PatriEfec { get; set; }
        [Column("patri_ahorro")]
        public double? PatriAhorro { get; set; }
        [Column("patri_ccobra")]
        public double? PatriCcobra { get; set; }
        [Column("patri_inven")]
        public double? PatriInven { get; set; }
        [Column("patri_maqui")]
        public double? PatriMaqui { get; set; }
        [Column("patri_terreno")]
        public double? PatriTerreno { get; set; }
        [Column("patri_vivienda")]
        public double? PatriVivienda { get; set; }
        [Column("patri_vehicu")]
        public double? PatriVehicu { get; set; }
        [Column("patri_telefo")]
        public double? PatriTelefo { get; set; }
        [Column("patri_banco")]
        public double? PatriBanco { get; set; }
        [Column("patri_coopera")]
        public double? PatriCoopera { get; set; }
        [Column("patri_cempe")]
        public double? PatriCempe { get; set; }
        [Column("patri_micro")]
        public double? PatriMicro { get; set; }
        [Column("patri_presta")]
        public double? PatriPresta { get; set; }
        [Column("patri_provee")]
        public double? PatriProvee { get; set; }
        [Column("patri_progob")]
        public double? PatriProgob { get; set; }
        [Column("patri_ccomer")]
        public double? PatriCcomer { get; set; }
        [Column("patri_antmerca")]
        public double? PatriAntmerca { get; set; }
        [Column("patri_fami")]
        public double? PatriFami { get; set; }
        [Column("patri_tactivo")]
        public double? PatriTactivo { get; set; }
        [Column("patri_tpasivo")]
        public double? PatriTpasivo { get; set; }
        [Column("codsolicitud")]
        [StringLength(255)]
        [Unicode(false)]
        public string Codsolicitud { get; set; }
        [Column("oingretotal")]
        public double? Oingretotal { get; set; }
    }
}