// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Loans.API.Models
{
    [Table("inventario")]
    public partial class Inventario
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idHash")]
        [StringLength(255)]
        [Unicode(false)]
        public string IdHash { get; set; }
        [Column("idSolicitud")]
        [StringLength(255)]
        [Unicode(false)]
        public string IdSolicitud { get; set; }
        [Column("fechaCompra", TypeName = "date")]
        public DateTime? FechaCompra { get; set; }
        [Column("descripcion")]
        [StringLength(255)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Column("cantidad")]
        public int? Cantidad { get; set; }
        [Column("precioUnitarioCompra")]
        public double? PrecioUnitarioCompra { get; set; }
        [Column("precioUnitarioVenta")]
        public double? PrecioUnitarioVenta { get; set; }
        [Column("costoTotal")]
        public double? CostoTotal { get; set; }
        [Column("ventaTotal")]
        public double? VentaTotal { get; set; }
        [Column("utilidad")]
        public double? Utilidad { get; set; }
        [Column("observaciones")]
        [StringLength(255)]
        [Unicode(false)]
        public string Observaciones { get; set; }
    }
}