// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Loans.API.Models
{
    [Table("solicitudes")]
    public partial class Solicitudes
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idHash")]
        [StringLength(255)]
        [Unicode(false)]
        public string IdHash { get; set; }
        [Column("codSolicitud")]
        [StringLength(255)]
        [Unicode(false)]
        public string CodSolicitud { get; set; }
        [Column("codAgencia")]
        [StringLength(255)]
        [Unicode(false)]
        public string CodAgencia { get; set; }
        [Column("codCliente")]
        [StringLength(255)]
        [Unicode(false)]
        public string CodCliente { get; set; }
        [Column("carnetImprema")]
        [StringLength(255)]
        [Unicode(false)]
        public string CarnetImprema { get; set; }
        [Column("prestamo")]
        [StringLength(255)]
        [Unicode(false)]
        public string Prestamo { get; set; }
        [Column("clase")]
        public int? Clase { get; set; }
        [Column("vlcuota")]
        public int? Vlcuota { get; set; }
        [Column("numCuotas")]
        public int? NumCuotas { get; set; }
        [Column("fechaSolicitud", TypeName = "datetime")]
        public DateTime? FechaSolicitud { get; set; }
        [Column("fechaDictamen", TypeName = "datetime")]
        public DateTime? FechaDictamen { get; set; }
        [Column("nivelManejo")]
        public int? NivelManejo { get; set; }
        [Column("codEstado")]
        public int? CodEstado { get; set; }
        [Column("montoSolicitado")]
        public int? MontoSolicitado { get; set; }
        [Column("montoAprobado")]
        public int? MontoAprobado { get; set; }
        [Column("saldoAport")]
        public int? SaldoAport { get; set; }
        [Column("nuevaAportacion")]
        public int? NuevaAportacion { get; set; }
        [Column("sueldoNeto")]
        public int? SueldoNeto { get; set; }
        [Column("sueldoMensual")]
        public int? SueldoMensual { get; set; }
        [Column("oficial")]
        public int? Oficial { get; set; }
        [Column("oficial2")]
        public int? Oficial2 { get; set; }
        [Column("marca")]
        [StringLength(255)]
        [Unicode(false)]
        public string Marca { get; set; }
        [Column("placa")]
        [StringLength(255)]
        [Unicode(false)]
        public string Placa { get; set; }
        [Column("operador")]
        [StringLength(255)]
        [Unicode(false)]
        public string Operador { get; set; }
        [Column("formaPgo")]
        public int? FormaPgo { get; set; }
        [Column("observaciones")]
        [StringLength(255)]
        [Unicode(false)]
        public string Observaciones { get; set; }
        [Column("planRet")]
        [StringLength(255)]
        [Unicode(false)]
        public string PlanRet { get; set; }
        [Column("anio")]
        public int? Anio { get; set; }
        [Column("frec")]
        public int? Frec { get; set; }
        [Column("tpCredito")]
        public int? TpCredito { get; set; }
        [Column("nivelE")]
        [StringLength(255)]
        [Unicode(false)]
        public string NivelE { get; set; }
        [Column("tpRenegociacion")]
        [StringLength(255)]
        [Unicode(false)]
        public string TpRenegociacion { get; set; }
        [Column("tipos")]
        public int? Tipos { get; set; }
        [Column("tpOperacion")]
        [StringLength(255)]
        [Unicode(false)]
        public string TpOperacion { get; set; }
        [Column("moneda")]
        public int? Moneda { get; set; }
        [Column("abonoPrev")]
        public int? AbonoPrev { get; set; }
        [Column("intProme")]
        public int? IntProme { get; set; }
        [Column("montoOriginal")]
        public int? MontoOriginal { get; set; }
        [Column("tpaval1")]
        public int? Tpaval1 { get; set; }
        [Column("tpaval2")]
        public int? Tpaval2 { get; set; }
        [Column("tpaval3")]
        public int? Tpaval3 { get; set; }
        [Column("tpaval4")]
        public int? Tpaval4 { get; set; }
        [Column("tpaval5")]
        public int? Tpaval5 { get; set; }
        [Column("aval1")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval1 { get; set; }
        [Column("aval2")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval2 { get; set; }
        [Column("aval3")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval3 { get; set; }
        [Column("aval4")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval4 { get; set; }
        [Column("aval5")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval5 { get; set; }
        [Column("cobertura1")]
        public int? Cobertura1 { get; set; }
        [Column("cobertura2")]
        public int? Cobertura2 { get; set; }
        [Column("cobertura3")]
        public int? Cobertura3 { get; set; }
        [Column("cobertura4")]
        public int? Cobertura4 { get; set; }
        [Column("cobertura5")]
        public int? Cobertura5 { get; set; }
        [Column("aval1Tpobligacion")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval1Tpobligacion { get; set; }
        [Column("aval2Tpobligacion")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval2Tpobligacion { get; set; }
        [Column("aval3Tpobligacion")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval3Tpobligacion { get; set; }
        [Column("aval4Tpobligacion")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval4Tpobligacion { get; set; }
        [Column("aval5Tpobligacion")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval5Tpobligacion { get; set; }
        [Column("aval1Tpgarantia")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval1Tpgarantia { get; set; }
        [Column("aval2Tpgarantia")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval2Tpgarantia { get; set; }
        [Column("aval3Tpgarantia")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval3Tpgarantia { get; set; }
        [Column("aval4Tpgarantia")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval4Tpgarantia { get; set; }
        [Column("aval5Tpgarantia")]
        [StringLength(255)]
        [Unicode(false)]
        public string Aval5Tpgarantia { get; set; }
        [Column("sueldoAval1")]
        public int? SueldoAval1 { get; set; }
        [Column("sueldoAval2")]
        public int? SueldoAval2 { get; set; }
        [Column("sueldoAval3")]
        public int? SueldoAval3 { get; set; }
        [Column("sueldoaval4")]
        public int? Sueldoaval4 { get; set; }
        [Column("sueldoaval5")]
        public int? Sueldoaval5 { get; set; }
        [Column("dictamen")]
        [StringLength(255)]
        [Unicode(false)]
        public string Dictamen { get; set; }
        [Column("fchSldo", TypeName = "datetime")]
        public DateTime? FchSldo { get; set; }
        [Column("fchCreado", TypeName = "datetime")]
        public DateTime? FchCreado { get; set; }
        [Column("fondo")]
        [StringLength(255)]
        [Unicode(false)]
        public string Fondo { get; set; }
        [Column("programa")]
        [StringLength(255)]
        [Unicode(false)]
        public string Programa { get; set; }
        [Column("codAct")]
        public int? CodAct { get; set; }
        [Column("area")]
        public int? Area { get; set; }
        [Column("fchAprobado", TypeName = "datetime")]
        public DateTime? FchAprobado { get; set; }
        [Column("aprobadoPor")]
        [StringLength(255)]
        [Unicode(false)]
        public string AprobadoPor { get; set; }
        [Column("quiebra")]
        public int? Quiebra { get; set; }
        [Column("quiebraRazon")]
        [StringLength(255)]
        [Unicode(false)]
        public string QuiebraRazon { get; set; }
        [Column("quiebraFch", TypeName = "datetime")]
        public DateTime? QuiebraFch { get; set; }
        [Column("arrestado")]
        public int? Arrestado { get; set; }
        [Column("arrestadoRazon")]
        [StringLength(255)]
        [Unicode(false)]
        public string ArrestadoRazon { get; set; }
        [Column("malCredito")]
        public int? MalCredito { get; set; }
        [Column("creditoRazon")]
        [StringLength(255)]
        [Unicode(false)]
        public string CreditoRazon { get; set; }
        [Column("manutencion")]
        public int? Manutencion { get; set; }
        [Column("razonManu")]
        [StringLength(255)]
        [Unicode(false)]
        public string RazonManu { get; set; }
        [Column("fchVencimiento", TypeName = "datetime")]
        public DateTime? FchVencimiento { get; set; }
        [Column("acta")]
        [StringLength(255)]
        [Unicode(false)]
        public string Acta { get; set; }
        [Column("codResultPrecal")]
        public int? CodResultPrecal { get; set; }
        [Column("origen")]
        [StringLength(255)]
        [Unicode(false)]
        public string Origen { get; set; }
        [Column("tasa")]
        public int? Tasa { get; set; }
        [Column("actualizaDireccion")]
        public int? ActualizaDireccion { get; set; }
        [Column("tprenegociaDias")]
        public int? TprenegociaDias { get; set; }
        [Column("prestamoRenegocia")]
        [StringLength(255)]
        [Unicode(false)]
        public string PrestamoRenegocia { get; set; }
        [Column("actualizaDatosclie")]
        public int? ActualizaDatosclie { get; set; }
        [Column("actualizaDatosneg")]
        public int? ActualizaDatosneg { get; set; }
        [Column("estadoSolic")]
        public int? EstadoSolic { get; set; }
    }
}