// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Users.API.Infraestructure.DBModels
{
    [Table("roles_permisos")]
    public partial class RolesPermisos
    {
        [Key]
        public int Id { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string IdHash { get; set; }
        [Column("Id_Role")]
        public int IdRole { get; set; }
        [Column("Id_Permiso")]
        public int IdPermiso { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreadoEn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ActualizadoEn { get; set; }

        [ForeignKey("IdPermiso")]
        [InverseProperty("RolesPermisos")]
        public virtual Permisos IdPermisoNavigation { get; set; }
        [ForeignKey("IdRole")]
        [InverseProperty("RolesPermisos")]
        public virtual Roles IdRoleNavigation { get; set; }
    }
}