// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Users.API.Infraestructure.DBModels
{
    [Table("usuarios")]
    public partial class Usuarios
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("User_Hash_Id")]
        [StringLength(255)]
        [Unicode(false)]
        public string UserHashId { get; set; }
        [Column("identificacionPersonal")]
        [StringLength(25)]
        [Unicode(false)]
        public string IdentificacionPersonal { get; set; }
        [Column("nombre")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nombre { get; set; }
        [Column("apellido")]
        [StringLength(80)]
        [Unicode(false)]
        public string Apellido { get; set; }
        [Column("nombreUsuario")]
        [StringLength(50)]
        [Unicode(false)]
        public string NombreUsuario { get; set; }
        [Column("correo")]
        [StringLength(100)]
        [Unicode(false)]
        public string Correo { get; set; }
        [Column("fechaNacimiento", TypeName = "date")]
        public DateTime? FechaNacimiento { get; set; }
        [Column("direccion")]
        [StringLength(100)]
        [Unicode(false)]
        public string Direccion { get; set; }
        [Column("telefonoMovil")]
        [StringLength(50)]
        [Unicode(false)]
        public string TelefonoMovil { get; set; }
        [Column("telefono")]
        [StringLength(50)]
        [Unicode(false)]
        public string Telefono { get; set; }
        [Column("nacionalidad")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nacionalidad { get; set; }
        [Column("paisActual")]
        [StringLength(50)]
        [Unicode(false)]
        public string PaisActual { get; set; }
        [Column("activo")]
        public byte? Activo { get; set; }
        [Column("fechaExpiracionUsuario", TypeName = "datetime")]
        public DateTime? FechaExpiracionUsuario { get; set; }
        [Column("creadoEn", TypeName = "datetime")]
        public DateTime? CreadoEn { get; set; }
        [Column("idUsuarioCreacion")]
        public int? IdUsuarioCreacion { get; set; }
        [Column("actualizadoEn", TypeName = "datetime")]
        public DateTime? ActualizadoEn { get; set; }
        [Column("idUsuarioActualizacion")]
        public int? IdUsuarioActualizacion { get; set; }
        [Column("correoVerificado")]
        public byte? CorreoVerificado { get; set; }
        [Column("prefijoGenero")]
        [StringLength(1)]
        [Unicode(false)]
        public string PrefijoGenero { get; set; }
        [Column("codAgencias")]
        [StringLength(100)]
        [Unicode(false)]
        public string CodAgencias { get; set; }
    }
}