// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Users.API.Infraestructure.DBModels
{
    [Table("usuario_roles")]
    public partial class UsuarioRoles
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idHash")]
        [StringLength(250)]
        [Unicode(false)]
        public string IdHash { get; set; }
        [Column("idRolHash")]
        [StringLength(250)]
        [Unicode(false)]
        public string IdRolHash { get; set; }
        [Column("idUserHash")]
        [StringLength(250)]
        [Unicode(false)]
        public string IdUserHash { get; set; }
        [Column("fechaCreacion", TypeName = "datetime")]
        public DateTime? FechaCreacion { get; set; }
        [Column("idUsuarioCreacion")]
        public int? IdUsuarioCreacion { get; set; }
        [Column("fechaActualizacion", TypeName = "datetime")]
        public DateTime? FechaActualizacion { get; set; }
        [Column("idUsuarioActualizacion")]
        public int? IdUsuarioActualizacion { get; set; }
        [Column("llave")]
        [StringLength(100)]
        [Unicode(false)]
        public string Llave { get; set; }
    }
}