// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Users.API.Infraestructure.DBModels
{
    [Table("usuario_foto")]
    public partial class UsuarioFoto
    {
        [Key]
        public int Id { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string IdHash { get; set; }
        [Column("Usuario_Hash_Id")]
        [StringLength(250)]
        [Unicode(false)]
        public string UsuarioHashId { get; set; }
        [Column("fotoPerfilPequeña")]
        [StringLength(250)]
        [Unicode(false)]
        public string FotoPerfilPequeña { get; set; }
        [Column("fotoPerfilMediana")]
        [StringLength(250)]
        [Unicode(false)]
        public string FotoPerfilMediana { get; set; }
        [Column("fotoPerfilGrande")]
        [StringLength(250)]
        [Unicode(false)]
        public string FotoPerfilGrande { get; set; }
        [Column("identificacionFrente")]
        [StringLength(250)]
        [Unicode(false)]
        public string IdentificacionFrente { get; set; }
        [Column("identificacionAtras")]
        [StringLength(250)]
        [Unicode(false)]
        public string IdentificacionAtras { get; set; }
    }
}