// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Logs.API.Models
{
    [Table("logs_acceso")]
    public partial class LogsAcceso
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("fecha")]
        public DateTime? Fecha { get; set; }
        [Column("usuario")]
        [StringLength(255)]
        public string Usuario { get; set; }
        [Column("ipAddress")]
        [StringLength(50)]
        public string IpAddress { get; set; }
        [Column("recurso")]
        [StringLength(255)]
        public string Recurso { get; set; }
        [Column("metodo")]
        [StringLength(10)]
        public string Metodo { get; set; }
        [Column("codigoRespuesta")]
        public int? CodigoRespuesta { get; set; }
        [Column("userAgent")]
        [StringLength(250)]
        [Unicode(false)]
        public string UserAgent { get; set; }
    }
}