// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Logs.API.Models
{
    [Table("logs_seguridad")]
    public partial class LogsSeguridad
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("fecha")]
        public DateTime? Fecha { get; set; }
        [Column("usuario")]
        [StringLength(255)]
        public string Usuario { get; set; }
        [Column("ipAddress")]
        [StringLength(50)]
        public string IpAddress { get; set; }
        [Column("evento")]
        [StringLength(255)]
        public string Evento { get; set; }
        [Column("resultado")]
        [StringLength(50)]
        public string Resultado { get; set; }
        [Column("userAgent")]
        [StringLength(250)]
        [Unicode(false)]
        public string UserAgent { get; set; }
    }
}