// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Logs.API.Models
{
    [Table("logs_aplicacion")]
    public partial class LogsAplicacion
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("fecha")]
        public DateTime? Fecha { get; set; }
        [Column("aplicacion")]
        [StringLength(255)]
        public string Aplicacion { get; set; }
        [Column("usuario")]
        [StringLength(255)]
        public string Usuario { get; set; }
        [Column("mensaje")]
        public string Mensaje { get; set; }
        [Column("nivel")]
        [StringLength(50)]
        public string Nivel { get; set; }
        [Column("detalles")]
        public string Detalles { get; set; }
    }
}