// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Auth.API.Infraestructura.DBModels
{
    [Table("ip_block")]
    public partial class IpBlock
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idUserHash")]
        [StringLength(100)]
        [Unicode(false)]
        public string IdUserHash { get; set; }
        [Column("ip")]
        [StringLength(50)]
        [Unicode(false)]
        public string Ip { get; set; }
        [Column("fechaBloqueo", TypeName = "datetime")]
        public DateTime? FechaBloqueo { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Motivo { get; set; }
        public int? Bloqueada { get; set; }
        [Column("userAgent")]
        [StringLength(500)]
        [Unicode(false)]
        public string UserAgent { get; set; }
    }
}