// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Auth.API.Infraestructura.DBModels
{
    [Table("login")]
    [Index("IdUserHash", Name = "UQ__login__249048DC02B15270", IsUnique = true)]
    public partial class Login
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idUserHash")]
        [StringLength(250)]
        [Unicode(false)]
        public string IdUserHash { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Correo { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string PasswordHash { get; set; }
        public bool PassReset { get; set; }
        [Column("creadoEn", TypeName = "datetime")]
        public DateTime CreadoEn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ActualizadoEn { get; set; }
    }
}