// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Auth.API.Infraestructura.DBModels
{
    [Table("tokens")]
    public partial class Tokens
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idUsuarioHash")]
        public int? IdUsuarioHash { get; set; }
        [Column("creadoEn", TypeName = "datetime")]
        public DateTime? CreadoEn { get; set; }
        [Column("expira", TypeName = "datetime")]
        public DateTime? Expira { get; set; }
        [Column("userAgent")]
        [StringLength(255)]
        [Unicode(false)]
        public string UserAgent { get; set; }
        [Column("ip")]
        [StringLength(255)]
        [Unicode(false)]
        public string Ip { get; set; }
    }
}