// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Auth.API.Infraestructura.DBModels
{
    [Table("usuario_sesiones")]
    public partial class UsuarioSesiones
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idUsuarioHash")]
        [StringLength(255)]
        [Unicode(false)]
        public string IdUsuarioHash { get; set; }
        [Column("idSession")]
        [StringLength(255)]
        [Unicode(false)]
        public string IdSession { get; set; }
        [Column("creadoEn", TypeName = "datetime")]
        public DateTime? CreadoEn { get; set; }
        [Column("actualizadoEn", TypeName = "datetime")]
        public DateTime? ActualizadoEn { get; set; }
    }
}